---
# defaults file for sa-box-jenkins

  root_dir: "{{ role_path }}"
  role_dir: "{{ role_path }}"

  option_use_pregenerated_pem: true
  option_serve_over_http: false

  jenkins_install_dir: /var/lib/jenkins

  jenkins_java_args: -Djava.awt.headless=true -Djenkins.install.runSetupWizard=false

  jenkins_connection_delay: 5
  jenkins_connection_retries: 60
  jenkins_hostname: localhost

  jenkins_admin_user: admin
  jenkins_admin_password: password
  # Admin and deploy users are REQUIRED. Feel free to redefine or amend passwords

  jenkins_users:
    - {
      name: "admin",
      password: "password",
      email: "no-reply@localhost"
      }


  jenkins_plugins:
    - bitbucket
    - bitbucket-pullrequest-builder
    - blueocean # https://wiki.jenkins-ci.org/display/JENKINS/Blue+Ocean+Plugin 
    - copyartifact # https://wiki.jenkins-ci.org/display/JENKINS/Copy+Artifact+Plugin
    - credentials # https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Plugin
    - git
    - junit # https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Plugin
    - parameterized-trigger #https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin
    - rebuild # https://wiki.jenkins-ci.org/display/JENKINS/Rebuild+Plugin
    - ssh
    - slack # https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin 
    - s3 # https://wiki.jenkins-ci.org/display/JENKINS/S3+Plugin
    - throttle-concurrents #https://wiki.jenkins-ci.org/display/JENKINS/Throttle+Concurrent+Builds+Plugin

  jenkins_url_prefix: ""

  jenkins_domain: "vagrant.dev"
  jenkins_host: "jenkins"

  ssl_key_fqdn:  "{{jenkins_host}}.{{jenkins_domain}}"
  ssl_key_name:  jenkins_selfsigned
  ssl_cert_name: jenkins_selfsigned
  ssl_install_path: /etc/nginx
  ssl_files:
    - "{{ssl_key_name}}.key"
    - "{{ssl_cert_name}}.crt"
